<a href="https://colab.research.google.com/github/ProfessorDong/Digital-Array/blob/main/Python_Cadence.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
from io import StringIO

data = """Vg_Bias(V)    -60    -55    -50    -45    -40    -35    -30    -25    -20    -19    -18    -17    -16    -15    -14    -13    -12    -11    -10    -9    -8    -7    -6    -5    -4    -3    -2    -1    0
0.350	-570.55	-510.55	-450.55	-390.65	-330.36	-269.75	-207.27	-137.47	-55.51	-43.04	-31.95	-21.65	-12.23	-4.61	0.58	4.12	6.92	9.35	11.51	13.34	14.96	16.44	17.82	19.09	20.23	21.33	23.70	28.54	31.75
0.375	-515.35	-455.35	-395.35	-335.35	-275.58	-215.97	-156.36	-93.83	-39.14	-30.13	-21.10	-12.55	-5.44	-0.26	3.42	6.32	8.84	11.01	12.91	14.55	16.07	17.42	18.68	19.79	20.88	21.84	23.93	28.65	31.77
0.400	-480.75	-420.75	-360.75	-300.75	-240.63	-180.60	-120.66	-67.98	-29.74	-21.17	-13.09	-6.26	-1.00	2.85	5.84	8.36	10.52	12.42	14.10	15.66	17.04	18.30	19.46	20.59	21.49	22.20	24.22	28.72	31.78
0.425	-465.40	-405.40	-345.40	-285.40	-225.63	-166.11	-107.78	-60.72	-21.38	-13.78	-7.07	-1.73	2.29	5.34	7.88	10.10	12.01	13.73	15.28	16.70	17.92	19.13	20.28	21.03	21.84	22.85	24.65	28.81	31.81
0.450	-452.60	-392.60	-332.60	-272.61	-212.85	-153.47	-96.17	-52.78	-14.50	-7.95	-2.47	1.78	4.95	7.47	9.63	11.57	13.33	14.92	16.36	17.60	18.80	19.89	20.85	21.78	22.41	23.37	24.97	28.88	31.83
0.475	-443.60	-383.60	-323.60	-263.64	-203.91	-144.80	-88.26	-46.64	-9.14	-3.36	1.21	4.63	7.26	9.41	11.17	12.86	14.48	16.00	17.32	18.44	19.49	20.49	21.28	22.15	23.09	23.94	25.25	28.95	31.85
0.500	-437.45	-377.45	-317.55	-257.70	-198.00	-138.99	-83.36	-42.30	-5.11	0.17	4.13	7.05	9.25	11.09	12.60	14.03	15.47	17.05	18.02	19.05	20.24	21.02	21.78	22.73	23.63	24.37	25.63	29.04	31.87
0.525	-433.70	-373.70	-313.70	-253.78	-194.10	-135.34	-80.58	-39.36	-2.22	2.76	6.41	9.06	11.01	12.60	13.95	15.11	16.48	17.61	18.71	19.71	20.64	21.51	22.28	23.04	23.89	24.98	25.76	29.10	31.88
0.550	-431.30	-371.30	-311.30	-251.40	-191.75	-133.07	-79.23	-37.60	-0.29	4.56	8.11	10.62	12.48	14.01	15.19	16.16	17.15	18.22	19.34	20.49	21.22	22.05	22.80	23.49	24.27	25.23	26.17	29.17	31.90
0.575	-430.05	-370.15	-310.15	-250.19	-190.72	-132.12	-78.94	-36.86	0.81	5.70	9.28	11.81	13.64	15.09	16.29	17.19	17.95	18.84	19.92	20.82	21.79	22.53	23.36	23.96	24.67	25.65	26.52	29.24	31.92
0.600	-429.85	-369.85	-309.85	-250.08	-190.49	-132.09	-79.47	-37.06	1.16	6.22	9.93	12.58	14.49	15.99	17.20	18.13	18.74	19.42	20.25	21.19	22.07	23.00	23.78	24.43	25.08	25.97	26.93	29.34	31.94
0.625	-430.45	-370.45	-310.60	-250.69	-191.26	-132.92	-80.77	-38.11	0.77	6.11	10.10	12.94	14.99	16.60	17.90	18.88	19.54	20.04	20.79	21.56	22.45	23.38	24.18	24.90	25.50	26.29	27.30	29.37	31.97
0.650	-432.10	-372.10	-312.20	-252.40	-192.99	-134.82	-82.93	-39.96	-0.29	5.35	9.72	12.91	15.20	16.93	18.36	19.45	20.21	20.69	21.21	21.93	22.76	23.73	24.57	25.32	25.94	26.58	27.55	29.48	31.99
0.675	-434.85	-374.85	-315.10	-255.16	-195.74	-137.83	-86.02	-42.57	-2.04	3.94	8.77	12.42	15.11	17.03	18.58	19.85	20.71	21.27	21.72	22.30	23.13	24.00	24.87	25.72	26.34	26.94	27.83	29.56	32.00
0.700	-439.05	-379.05	-319.15	-259.33	-200.01	-142.12	-90.07	-45.94	-4.41	1.94	7.28	11.50	14.64	16.87	18.59	20.03	21.03	21.75	22.21	22.70	23.38	24.20	25.15	26.01	26.74	27.31	28.13	29.61	32.02
0.725	-444.50	-384.50	-324.50	-264.71	-205.31	-147.34	-95.04	-50.07	-7.39	-0.63	5.22	10.07	13.78	16.49	18.40	19.98	21.16	22.06	22.61	23.10	23.66	24.44	25.30	26.25	27.08	27.67	28.33	29.70	32.04
0.750	-450.80	-390.80	-330.80	-270.99	-211.54	-153.58	-100.79	-54.94	-10.94	-3.74	2.65	8.15	12.55	15.78	18.00	19.82	21.24	22.25	23.01	23.41	23.96	24.60	25.44	26.39	27.30	27.99	28.55	29.77	32.06
0.775	-457.75	-397.75	-337.75	-277.95	-218.68	-160.61	-107.36	-60.59	-15.01	-7.32	-0.40	5.73	10.89	14.74	17.49	19.47	21.13	22.35	23.18	23.75	24.16	24.77	25.57	26.50	27.48	28.27	28.81	29.86	32.09
0.800	-466.25	-406.25	-346.40	-286.63	-227.05	-168.95	-114.98	-67.05	-19.56	-11.35	-3.85	2.91	8.79	13.43	16.71	18.98	20.94	22.27	23.28	23.98	24.43	24.96	25.76	26.59	27.58	28.50	29.05	29.96	32.11
0.825	-476.85	-416.85	-356.85	-296.98	-237.47	-178.85	-123.72	-74.36	-24.54	-15.74	-7.65	-0.27	6.30	11.77	15.67	18.44	20.52	22.17	23.37	24.09	24.59	25.10	25.81	26.69	27.67	28.67	29.29	30.06	32.13
0.850	-487.95	-427.95	-367.95	-308.06	-248.37	-189.49	-133.28	-82.36	-29.83	-20.38	-11.68	-3.72	3.53	9.76	14.45	17.65	19.98	21.92	23.40	24.18	24.81	25.27	25.90	26.75	27.72	28.77	29.50	30.16	32.15
0.875	-498.00	-438.00	-378.00	-318.25	-258.48	-199.60	-142.88	-90.91	-35.41	-25.16	-15.84	-7.30	0.50	7.43	12.98	16.72	19.29	21.54	23.08	24.24	24.97	25.42	26.02	26.88	27.79	28.83	29.69	30.27	32.17
0.900	-507.35	-447.35	-387.35	-327.45	-267.94	-209.11	-152.49	-99.77	-41.20	-29.92	-19.83	-10.82	-2.57	4.95	11.29	15.72	18.66	21.02	22.83	24.20	25.08	25.62	26.18	26.89	27.82	28.87	29.84	30.40	32.20
0.925	-519.10	-459.10	-399.10	-339.20	-279.39	-220.21	-162.57	-108.90	-47.52	-34.66	-23.33	-13.81	-5.39	2.45	9.42	14.58	17.89	20.44	22.51	24.06	25.14	25.76	26.24	26.96	27.91	28.89	29.95	30.53	32.22
0.950	-534.50	-474.50	-414.50	-354.50	-294.60	-234.63	-175.22	-118.71	-55.68	-40.74	-26.23	-15.39	-7.29	0.34	7.56	13.41	17.13	19.82	22.08	23.91	25.08	25.89	26.37	27.11	28.01	28.94	30.01	30.65	32.24
"""

# Rows are Vg Bias (V); Columns are Input Tone Power (dBm)
# 10*Pout(dBm) - IMD3(dBm)  = the higher the better

# Read the data into a pandas DataFrame
data_io = StringIO(data)
df = pd.read_csv(data_io, sep='\s+', index_col=0)

# Display the DataFrame
print(df)

               -60     -55     -50     -45     -40     -35     -30     -25  \
Vg_Bias(V)                                                                   
0.350      -570.55 -510.55 -450.55 -390.65 -330.36 -269.75 -207.27 -137.47   
0.375      -515.35 -455.35 -395.35 -335.35 -275.58 -215.97 -156.36  -93.83   
0.400      -480.75 -420.75 -360.75 -300.75 -240.63 -180.60 -120.66  -67.98   
0.425      -465.40 -405.40 -345.40 -285.40 -225.63 -166.11 -107.78  -60.72   
0.450      -452.60 -392.60 -332.60 -272.61 -212.85 -153.47  -96.17  -52.78   
0.475      -443.60 -383.60 -323.60 -263.64 -203.91 -144.80  -88.26  -46.64   
0.500      -437.45 -377.45 -317.55 -257.70 -198.00 -138.99  -83.36  -42.30   
0.525      -433.70 -373.70 -313.70 -253.78 -194.10 -135.34  -80.58  -39.36   
0.550      -431.30 -371.30 -311.30 -251.40 -191.75 -133.07  -79.23  -37.60   
0.575      -430.05 -370.15 -310.15 -250.19 -190.72 -132.12  -78.94  -36.86   
0.600      -429.85 -369.85 -309.85 -250.08 -190.49 -132.09  -79.

In [2]:
# Convert Data Frame to Python Array
data = df.values
print(data.shape)
print(f"First row:", data[0])
print(f"First column:", data[:, 0])

(25, 29)
First row: [-570.55 -510.55 -450.55 -390.65 -330.36 -269.75 -207.27 -137.47  -55.51
  -43.04  -31.95  -21.65  -12.23   -4.61    0.58    4.12    6.92    9.35
   11.51   13.34   14.96   16.44   17.82   19.09   20.23   21.33   23.7
   28.54   31.75]
First column: [-570.55 -515.35 -480.75 -465.4  -452.6  -443.6  -437.45 -433.7  -431.3
 -430.05 -429.85 -430.45 -432.1  -434.85 -439.05 -444.5  -450.8  -457.75
 -466.25 -476.85 -487.95 -498.   -507.35 -519.1  -534.5 ]


In [12]:
import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np

# Generate input data (Vg_Bias and Input_Tone_Power)
vg_bias = np.linspace(0.350, 0.950, 25)
# input_tone_power = np.linspace(-60, 0, 29)
input_tone_power = [-60.,  -55., -50., -45., -40., -35., -30., -25., -20., -19., -18., -17., -16., -15., -14., -13., -12., -11., -10., -9., -8., -7., -6., -5., -4., -3., -2., -1., 0]
X = np.array([[vb, itp] for vb in vg_bias for itp in input_tone_power], dtype=np.float32)
y = data.flatten().astype(np.float32)

# Convert to PyTorch tensors
X_tensor = torch.from_numpy(X)
y_tensor = torch.from_numpy(y)

display(X_tensor)
print("Shape of X_tensor: ", X_tensor.shape)
print("Shape of y_tensor: ", y_tensor.shape)

tensor([[  0.3500, -60.0000],
        [  0.3500, -55.0000],
        [  0.3500, -50.0000],
        ...,
        [  0.9500,  -2.0000],
        [  0.9500,  -1.0000],
        [  0.9500,   0.0000]])

Shape of X_tensor:  torch.Size([725, 2])
Shape of y_tensor:  torch.Size([725])


In [13]:
# New data points
new_X = np.array([[0.7, -14.], [0.8, -14.]], dtype=np.float32)
new_y= np.array([16.69, 16.4], dtype=np.float32)
new_X_tensor = torch.from_numpy(new_X)
new_y_tensor = torch.from_numpy(new_y)

display(new_X_tensor)
print("Shape of new_X_tensor: ", new_X_tensor.shape)
print("Shape of new_y_tensor: ", new_y_tensor.shape)

# Append new data
X_tensor = torch.cat((X_tensor, new_X_tensor), dim=0)
y_tensor = torch.cat((y_tensor, new_y_tensor), dim=0)

display(X_tensor)
print("Shape of X_tensor: ", X_tensor.shape)
# display(y_tensor)
print("Shape of y_tensor: ", y_tensor.shape)

tensor([[  0.7000, -14.0000],
        [  0.8000, -14.0000]])

Shape of new_X_tensor:  torch.Size([2, 2])
Shape of new_y_tensor:  torch.Size([2])


tensor([[  0.3500, -60.0000],
        [  0.3500, -55.0000],
        [  0.3500, -50.0000],
        ...,
        [  0.9500,   0.0000],
        [  0.7000, -14.0000],
        [  0.8000, -14.0000]])

Shape of X_tensor:  torch.Size([727, 2])
Shape of y_tensor:  torch.Size([727])


In [5]:
# Define the neural network
class NeuralNetwork(nn.Module):
    def __init__(self):
        super(NeuralNetwork, self).__init__()
        self.layer1 = nn.Linear(2, 64)
        self.layer2 = nn.Linear(64, 64)
        self.output_layer = nn.Linear(64, 1)

    def forward(self, x):
        x = torch.relu(self.layer1(x))
        x = torch.relu(self.layer2(x))
        return self.output_layer(x)

In [6]:
print(vg_bias)
print(input_tone_power)
print(len(input_tone_power))

[0.35  0.375 0.4   0.425 0.45  0.475 0.5   0.525 0.55  0.575 0.6   0.625
 0.65  0.675 0.7   0.725 0.75  0.775 0.8   0.825 0.85  0.875 0.9   0.925
 0.95 ]
[-60.0, -55.0, -50.0, -45.0, -40.0, -35.0, -30.0, -25.0, -20.0, -19.0, -18.0, -17.0, -16.0, -15.0, -14.0, -13.0, -12.0, -11.0, -10.0, -9.0, -8.0, -7.0, -6.0, -5.0, -4.0, -3.0, -2.0, -1.0, 0]
29


In [7]:
# Instantiate the model, loss function and optimizer
model = NeuralNetwork()
criterion = nn.MSELoss()
optimizer = optim.Adam(model.parameters(), lr=0.0001)

# Training the model
for epoch in range(500000):
    optimizer.zero_grad()
    outputs = model(X_tensor).squeeze()
    loss = criterion(outputs, y_tensor)
    loss.backward()
    optimizer.step()
    if (epoch + 1) % 1000 == 0:
        print(f'Epoch [{epoch+1}/500000], Loss: {loss.item()}')

Epoch [1000/500000], Loss: 7152.9658203125
Epoch [2000/500000], Loss: 2375.41015625
Epoch [3000/500000], Loss: 1816.3060302734375
Epoch [4000/500000], Loss: 1463.5670166015625
Epoch [5000/500000], Loss: 1029.4315185546875
Epoch [6000/500000], Loss: 715.3193359375
Epoch [7000/500000], Loss: 558.8568115234375
Epoch [8000/500000], Loss: 502.9337463378906
Epoch [9000/500000], Loss: 476.6367492675781
Epoch [10000/500000], Loss: 448.62664794921875
Epoch [11000/500000], Loss: 424.65960693359375
Epoch [12000/500000], Loss: 407.1854248046875
Epoch [13000/500000], Loss: 394.29547119140625
Epoch [14000/500000], Loss: 385.7594909667969
Epoch [15000/500000], Loss: 380.3376159667969
Epoch [16000/500000], Loss: 373.8608093261719
Epoch [17000/500000], Loss: 355.12542724609375
Epoch [18000/500000], Loss: 338.545654296875
Epoch [19000/500000], Loss: 270.475341796875
Epoch [20000/500000], Loss: 220.32211303710938
Epoch [21000/500000], Loss: 169.9135284423828
Epoch [22000/500000], Loss: 140.05067443847656

In [8]:
# Use the trained model to make predictions
new_input = torch.tensor([[0.400, -48]], dtype=torch.float32)

predicted_imd3_distortion = model(new_input).item()
print(f"Predicted IMD3 Distortion: {predicted_imd3_distortion}")

Predicted IMD3 Distortion: -335.9605712890625
